rgname = "data-product"
location = "eastus"
adb_vnet = "adb-vnet"
adb_vnet_address_space = ["10.0.0.0/24"]
adb_private_subnet = "adb-private-subnet"
adb_public_subnet = "adb-public-subnet"
adb_private_subnet_address_space = ["10.0.0.0/26"]
adb_public_subnet_address_space = ["10.0.0.64/26"]
adb_nsg = "adb-nsg"
adb_ws= "adb-dataproduct-ws"
dp_datastore = "srdpdatastore"
adb_global_init_path = "./global_init/global_init.sh"
kvname = "data-product-kv"
